// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

namespace server.Migrations
{
    [DbContext(typeof(JobsContext))]
    [Migration("20211212204211_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("server.Models.Employer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PIB");

                    b.Property<string>("address");

                    b.Property<string>("description");

                    b.Property<string>("imageUrl");

                    b.Property<string>("name");

                    b.Property<string>("phone");

                    b.Property<string>("website");

                    b.HasKey("id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("server.Models.JobListing", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateCreated");

                    b.Property<DateTime>("deadline");

                    b.Property<string>("description");

                    b.Property<long>("employerId");

                    b.Property<string>("linkToApply");

                    b.Property<string>("location");

                    b.Property<string>("seniority");

                    b.Property<string>("tags");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("JobListings");
                });
#pragma warning restore 612, 618
        }
    }
}
